apiVersion: v1
kind: Service
metadata:
  name: aggregate-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: aggregate-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aggregate-service-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: aggregate-service
    spec:
      containers:
      - name: aggregate-service
        image: smarterbalanced/rdw-reporting-aggregate-service:1.2.0-RELEASE
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 500m
            memory: 850M
          limits:
            cpu: 500m
            memory: 850M
        env:
        - name: CONFIG_SERVICE_URL
          value: "http://configuration-service"
        - name: CONFIG_SERVICE_ENABLED
          value: "true"
        - name: MAX_HEAP_SIZE
          value: "-Xmx600m"
        ports:
        - containerPort: 8080
        - containerPort: 8008
