apiVersion: v1
kind: Service
metadata:
  name: reporting-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: api
  selector:
    app: reporting-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reporting-service-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      containers:
      - name: reporting-service
        image: smarterbalanced/rdw-reporting-service:1.4.0-RELEASE
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 500m
            memory: 750M
          limits:
            cpu: 500m
            memory: 750M
        env:
        - name: CONFIG_SERVICE_URL
          value: "http://configuration-service"
        - name: CONFIG_SERVICE_ENABLED
          value: "true"
        - name: MAX_HEAP_SIZE
          value: "-Xmx500m"
        ports:
        - containerPort: 8080
        - containerPort: 8008
        volumeMounts:
        - mountPath: /itembank
          name: itembank
      volumes:
      - name: itembank
        persistentVolumeClaim:
          claimName: iris-efs-volume
