apiVersion: v1
kind: Service
metadata:
  name: report-processor-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: report-processor
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: report-processor-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 2
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: report-processor
    spec:
      containers:
      - name: report-processor
        image: smarterbalanced/rdw-reporting-report-processor:1.2.1-RELEASE
        readinessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 200m
            memory: 800M
          limits:
            cpu: 300m
            memory: 800M
        env:
        - name: CONFIG_SERVICE_URL
          value: "http://configuration-service"
        - name: CONFIG_SERVICE_ENABLED
          value: "true"
        - name: MAX_HEAP_SIZE
          value: "-Xmx512m"
        ports:
        - containerPort: 8080
        - containerPort: 8008
