# Annotated configuration for RDW Task Service

# Task configuration.
# By default, all tasks are disabled.
# The cron syntax is slightly different than standard linux cron syntax. The pattern is a list
# of six single space-separated fields: representing second, minute, hour, day, month, weekday.
# Month and weekday names can be given as the first three letters of the English names.
# Example patterns:
#   0 0 10 * * *           10 AM every day
#   0 0 * * * *            the top of every hour of every day
#   */10 * * * * *         every ten seconds
#   0 0 8-10 * * *         8, 9 and 10 o'clock of every day
#   0 0 6,19 * * *         6:00 AM and 7:00 PM every day
#   0 0/30 8-10 * * *      8:00, 8:30, 9:00, 9:30, 10:00 and 10:30 every day
#   0 0 9-17 * * MON-FRI   on the hour nine-to-five weekdays
#   0 0 0 25 12 ?          every Christmas Day at midnight
# Note that all times are in GMT, regardless of the system's timezone setting.

task:
  # Reconciliation Report configuration.
  send-reconciliation-report:
    cron: 0 0 12 * * *
    query: status=PROCESSED&after=-PT24H
    # This sample has many senders for illustration purposes. In a real deployment it is likely
    # there will be a single sender (and, perhaps the log sender for monitoring/diagnostics).
    senders:
      - type: log
      - type: archive
        uri-root: file:///tmp/
        # The S3 archive sender has the same configuration options as an archive service. The
        # uri-root should be the protocol and bucket, e.g. s3://my-archive-bucket. The AWS access
        # key should be for a programmatic AWS user. The secret key should be encrypted. The sse
        # setting is optional and should correspond to the S3 bucket settings.
      - type: archive
        uri-root:
        s3-access-key:
        s3-secret-key:
        s3-region-static: us-west-2
        s3-sse: AES256
      - type: ftp
        server:
        username:
        password:

  # Update Organizations configuration
  update-organizations:
    cron: 0 0 8 * * *
    state: CA
    art-client:
      groups-of-districts-url: https://art.smarterbalanced.org/rest/groupofdistrict?stateAbbreviation={state}&pageSize=1000
      districts-url: https://art.smarterbalanced.org/rest/district?stateAbbreviation={state}&pageSize=5000
      groups-of-schools-url: https://art.smarterbalanced.org/rest/groupofinstitution?stateAbbreviation={state}&pageSize=1000
      schools-url: https://art.smarterbalanced.org/rest/institution?stateAbbreviation={state}&pageSize=20000
      status-url: https://art.smarterbalanced.org/rest/status
      # The credentials should be for a user that has access to the ART REST API
      oauth2:
        access-token-uri: https://sso.smarterbalanced.org/auth/oauth2/access_token?realm=/sbac
        client-id:
        client-secret:
        username:
        password:
    import-service-client:
      organizations-imports-url: http://import-service/organizations/imports
      status-url: http://import-status-service/status
      # The credentials should be for a user that has ASMTDATALOAD privileges for the import REST API
      oauth2:
        access-token-uri: https://sso.smarterbalanced.org/auth/oauth2/access_token?realm=/sbac
        client-id:
        client-secret:
        username:
        password:
