# Annotated configuration for RDW Import Service.

# OAuth2 configuration.
# Provider is used to specify a provider between OpenAm and Okta.
#     provider: okta
# The OAuth2 URL is used to fetch info for the token, so it must have a placeholder for the token.
# For example, https://host/auth/oauth2/tokeninfo?access_token={access_token}.
security:
  oauth2:
    # provider: okta  # integrates with Okta. Any other setting or leaving provider out defaults to OpenAM.
    provider:
    # For Okta, the The OAuth2 URL is used to fetch a key to validate the access token. For example:
    # token-info-url: https://smarterbalanced.oktapreview.com/oauth2/auslw2qcsmsUgzsqr0h7info
    # For OpenAM, it used to fetch information for the token so it must have a placeholder for the token. For example:
    # token-info-url: https://host/auth/oauth2/tokeninfo?access_token={access_token}.
    # There is no default value for the URL, it must be provided.
    token-info-url:
    # Audience is only relevant for the Okta integration. It must match the audience value delivered in
    # the access token, and will vary by environment. For example: audience: api://staging or
    # audience: app://production
    audience:
    # Connection timeout is only relevant for the Okta integration and controls how long Okta will attempt to
    # connect to its server to download the validation keys. This defaults to 1000 (ms) and it should not be
    # necessary to set it in most cases.
    connection-timeout:
  #The permission-service end-point should correspond to the
  # RESTful interface, for example https://host/rest.
  permission-service:
    endpoint:
